# metricdf.pyi
from typing import IO, Any

import pandas as pd

class MetricDF(pd.DataFrame):
    def __init__(
        self,
        data: pd.DataFrame | dict | MetricDF | Any | None = None,
        *,
        coerce: bool = True,
        strict: bool = True,
        **kwargs: Any,
    ) -> None: ...
    def __new__(
        cls: type[MetricDF],
        data: pd.DataFrame | dict | MetricDF | Any | None = None,
        *,
        coerce: bool = True,
        strict: bool = True,
        **kwargs: Any,
    ) -> MetricDF: ...
    @classmethod
    def from_source(cls, src: str | IO[bytes]) -> MetricDF: ...
    def add_combinations(self, src: str | list[tuple[str, ...]]) -> MetricDF: ...
    @property
    def instance_id(self) -> pd.Series[int]: ...
    @property
    def filename(self) -> pd.Series[str]: ...
    @property
    def level(self) -> pd.Series[int]: ...
    @property
    def label(self) -> pd.Series[str]: ...
    @property
    def prediction(self) -> pd.Series[str]: ...
    @property
    def confidence(self) -> pd.Series[float]: ...
    @property
    def threshold(self) -> pd.Series[float]: ...
    @property
    def prediction_made(self) -> pd.Series[bool]: ...
    @property
    def known_label(self) -> pd.Series[bool]: ...
    @property
    def correct(self) -> pd.Series[int]: ...
    @property
    def prediction_level(self) -> pd.Series[int]: ...
