# metricdf.pyi
from typing import IO

import pandas

class MetricDF(pandas.DataFrame):
    @classmethod
    def from_source(cls, src : str | IO[bytes]) -> "MetricDF": ...
    @property
    def instance_id(self) -> pandas.Series[int]: ...
    @property
    def filename(self) -> pandas.Series[str]: ...
    @property
    def level(self) -> pandas.Series[int]: ...
    @property
    def label(self) -> pandas.Series[int]: ...
    @property
    def prediction(self) -> pandas.Series[int]: ...
    @property
    def confidence(self) -> pandas.Series[float]: ...
    @property
    def threshold(self) -> pandas.Series[float]: ...
    @property
    def prediction_made(self) -> pandas.Series[int]: ...
    @property
    def correct(self) -> pandas.Series[int]: ...
    @property
    def prediction_level(self) -> pandas.Series[int]: ...